# from enum import Enum

SERVER_IP = "127.0.0.1"
SERVER_PORT = 6000
BUFFER_SIZE = 4096
DATA_SIZE = 3682
STORAGE_LOCATION = "stored_files"

STOP_AND_WAIT = "sw"
SELECTIVE_REPEAT = "sr"

UPLOAD_TYPE = 1
DOWNLOAD_TYPE = 2

# FLAGS
NO_FLAG = 0
SYN = 1
START_TRANSFER = 2

# class Flags(Enum):
#     NO_FLAG = 0
#     SYN = 1
#     START_TRANSFER = 2