# from enum import Enum

SERVER_IP = "127.0.0.1"
SERVER_PORT = 6000
BUFFER_SIZE = 4096
DATA_SIZE = BUFFER_SIZE - 14
STORAGE_LOCATION = "stored_files"
DESTINATION_LOCATION = "downloaded_files"

STOP_AND_WAIT = "sw"
SELECTIVE_REPEAT = "sr"

UPLOAD_TYPE = 1
DOWNLOAD_TYPE = 2 

TIMEOUT_SECONDS = 5
# Timeouts en segundos
CONNECTION_TIMEOUT = 10
PKG_TIMEOUT = 0.2

# FLAGS
NO_FLAG = 0
SYN = 1
START_TRANSFER = 2
FIN = 3
ACK = 4